/**
 * Chat & RAG Type Definitions
 * This file defines the data structures for the chat interface, including
 * messages, sessions, source citations, and the contracts for RAG (Retrieval-Augmented Generation)
 * requests and responses.
 */

// ------------------------------------------------------------------
// Core Chat Entities
// ------------------------------------------------------------------

/**
 * Represents a single message in a chat conversation.
 * Mirrors the Firestore structure at `/users/{userId}/documents/{documentId}/chats/{chatId}/messages/{messageId}`.
 */
export interface Message {
  /** Unique identifier for the message */
  id: string;

  /** ID of the chat session this message belongs to */
  chatId: string;

  /** The role of the message sender */
  role: MessageRole;

  /** The text content of the message */
  content: string;

  /**
   * Source citations supporting the assistant's response.
   * Empty for user messages or if no sources were found.
   */
  citations?: Citation[];

  /** ISO 8601 timestamp of creation */
  createdAt: Date | string;

  /** Indicates if this message represents an error state */
  isError?: boolean;

  /** Human-readable error message if isError is true */
  errorMessage?: string;
}

/**
 * The role of the message sender.
 */
export type MessageRole = "user" | "assistant";

/**
 * Represents a persistent chat session associated with a document.
 * Mirrors the Firestore structure at `/users/{userId}/documents/{documentId}/chats/{chatId}`.
 */
export interface ChatSession {
  /** Unique identifier for the session */
  id: string;

  /** ID of the document context for this chat */
  documentId: string;

  /** ID of the user who owns this session */
  userId: string;

  /** Total number of messages in the thread (denormalized count) */
  messageCount: number;

  /** ISO 8601 timestamp of creation */
  createdAt: Date | string;

  /** ISO 8601 timestamp of last update */
  updatedAt: Date | string;
}

// ------------------------------------------------------------------
// RAG & Citation Types
// ------------------------------------------------------------------

/**
 * A reference to a specific part of a source document used to generate an answer.
 */
export interface Citation {
  /** ID of the source document */
  documentId: string;

  /** Name of the document (for display) */
  documentName: string;

  /** Page number where the information was found (1-based) */
  pageNumber: number;

  /**
   * The actual text snippet from the document chunk.
   * Optional/Growth feature for showing exact context.
   */
  chunkText?: string;

  /**
   * Similarity score from the vector search (0.0 - 1.0).
   * Higher is more relevant.
   */
  relevanceScore?: number;
}

// ------------------------------------------------------------------
// API Request/Response Contracts
// ------------------------------------------------------------------

/**
 * Payload for sending a message to the chat endpoint.
 * POST /v1/documents/:id/chat
 */
export interface ChatRequest {
  /** The natural language question or statement */
  message: string;

  /**
   * Optional ID of an existing session to continue.
   * If omitted, a new session is created.
   */
  sessionId?: string;
}

/**
 * Data payload returned by the chat endpoint.
 * Wrapped in ApiResponse<ChatResponse>.
 */
export interface ChatResponse {
  /** The ID of the session (new or existing) */
  sessionId: string;

  /** The complete message object generated by the assistant */
  message: Message;
}
