import 'package:hive_flutter/hive_flutter.dart';
import '../core/constants/storage_keys.dart';
import '../../features/documents/domain/entities/document.dart';
import '../../features/chat/domain/entities/message.dart';
import '../../features/chat/domain/entities/citation.dart';

/// Service responsible for local data persistence using Hive.
/// Handles offline caching for documents, messages, and app settings.
class StorageService {
  static final StorageService _instance = StorageService._internal();

  factory StorageService() => _instance;

  StorageService._internal();

  late Box<Document> _documentsBox;
  late Box<Message> _messagesBox;
  late Box _settingsBox;

  bool _isInitialized = false;

  /// Initializes Hive, registers adapters, and opens boxes.
  /// Must be called before any other method.
  Future<void> init() async {
    if (_isInitialized) return;

    await Hive.initFlutter();

    // Register Hive Adapters
    // Note: These adapters are generated by build_runner
    Hive.registerAdapter(DocumentAdapter());
    Hive.registerAdapter(MessageAdapter());
    Hive.registerAdapter(CitationAdapter());

    // Open Boxes
    _documentsBox = await Hive.openBox<Document>(StorageKeys.documentsBox);
    _messagesBox = await Hive.openBox<Message>(StorageKeys.messagesBox);
    _settingsBox = await Hive.openBox(StorageKeys.settingsBox);

    _isInitialized = true;
  }

  /// Saves a list of documents to the local cache.
  /// This overwrites existing documents with the same ID.
  Future<void> saveDocuments(List<Document> documents) async {
    _checkInitialized();
    final Map<String, Document> documentMap = {
      for (var doc in documents) doc.id: doc,
    };
    await _documentsBox.putAll(documentMap);
  }

  /// Retrieves all cached documents.
  Future<List<Document>> getDocuments() async {
    _checkInitialized();
    return _documentsBox.values.toList();
  }

  /// Saves messages for a specific chat.
  /// Appends new messages or updates existing ones based on ID.
  Future<void> saveMessages(String chatId, List<Message> messages) async {
    _checkInitialized();
    final Map<String, Message> messageMap = {
      for (var msg in messages) msg.id: msg,
    };
    await _messagesBox.putAll(messageMap);
  }

  /// Retrieves cached messages for a specific chat ID.
  Future<List<Message>> getMessages(String chatId) async {
    _checkInitialized();
    // Filter messages belonging to the specific chat session
    return _messagesBox.values.where((msg) => msg.chatId == chatId).toList();
  }

  /// Saves a setting value (e.g., theme mode).
  Future<void> saveSetting(String key, dynamic value) async {
    _checkInitialized();
    await _settingsBox.put(key, value);
  }

  /// Retrieves a setting value by key.
  T? getSetting<T>(String key) {
    _checkInitialized();
    return _settingsBox.get(key) as T?;
  }

  /// Clears all data from the cache (e.g., on logout).
  Future<void> clearCache() async {
    _checkInitialized();
    await _documentsBox.clear();
    await _messagesBox.clear();
    await _settingsBox.clear();
  }

  void _checkInitialized() {
    if (!_isInitialized) {
      throw Exception(
        'StorageService must be initialized before use. Call init() first.',
      );
    }
  }
}
